CREATE TABLE "week2-chatbot_account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "week2-chatbot_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "week2-chatbot_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "week2-chatbot_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "week2-chatbot_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "week2-chatbot_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "week2-chatbot_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "week2-chatbot_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "week2-chatbot_chat" ADD COLUMN "userId" text NOT NULL;--> statement-breakpoint
ALTER TABLE "week2-chatbot_account" ADD CONSTRAINT "week2-chatbot_account_user_id_week2-chatbot_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."week2-chatbot_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "week2-chatbot_session" ADD CONSTRAINT "week2-chatbot_session_user_id_week2-chatbot_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."week2-chatbot_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "week2-chatbot_post" USING btree ("name");--> statement-breakpoint
ALTER TABLE "week2-chatbot_chat" ADD CONSTRAINT "week2-chatbot_chat_userId_week2-chatbot_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."week2-chatbot_user"("id") ON DELETE no action ON UPDATE no action;